<a href="https://colab.research.google.com/github/pushpendracse/DataAnalyst/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## You have been hired by a rookie movie producer to help him decide what type of movies to produce and which actors to cast. You have to back your recommendations based on thorough analysis of the data he shared with you which has the list of 3000 movies and the corresponding details.

## As a data scientist, you have to first explore the data and check its sanity.

## Further, you have to answer the following questions:
1. ### <b> Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.</b>
2. ### <b>This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)? </b>
3. ### <b> Find out the unique genres of movies in this dataset.</b>

4. ### <b> Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor. </b>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
path = '/content/drive/MyDrive/Colab Notebooks/Data Set/imdb_data.csv'
df = pd.read_csv(path)
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

#Q1.Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.

In [ ]:
df['profit'] = df['revenue'] - df['budget']
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970

In [ ]:
df[df['profit'] == df['profit'].max()][['original_title']]

     original_title
1761      Furious 7

In [ ]:
df.loc[:5,'original_title']

0                      Hot Tub Time Machine 2
1    The Princess Diaries 2: Royal Engagement
2                                    Whiplash
3                                     Kahaani
4                                        마린보이
5      Pinocchio and the Emperor of the Night
Name: original_title, dtype: object

In [ ]:
max_profit_movie_name = df.loc[df['profit'].idxmax(),'original_title']
max_profit_movie_name

'Furious 7'

In [ ]:
df.iloc[1761]

id                                                                    1762
belongs_to_collection    [{'id': 9485, 'name': 'The Fast and the Furiou...
budget                                                           190000000
genres                                      [{'id': 28, 'name': 'Action'}]
homepage                                          http://www.furious7.com/
imdb_id                                                          tt2820852
original_language                                                       en
original_title                                                   Furious 7
overview                 Deckard Shaw seeks revenge against Dominic Tor...
popularity                                                       27.275687
poster_path                               /dCgm7efXDmiABSdWDHBDBx2jwmn.jpg
production_companies     [{'name': 'Universal Pictures', 'id': 33}, {'n...
production_countries     [{'iso_3166_1': 'JP', 'name': 'Japan'}, {'iso_...
release_date                                                        4/1/15
runtime                                                              137.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                                                Vengeance Hits Home
title                                                            Furious 7
Keywords                 [{'id': 830, 'name': 'car race'}, {'id': 3428,...
cast                     [{'cast_id': 17, 'character': 'Dominic Toretto...
crew                     [{'credit_id': '52fe4cc8c3a36847f823e681', 'de...
revenue                                                         1506249360
profit                                                          1316249360
Name: 1761, dtype: object

In [ ]:
df['profit'].idxmax()

1761

In [ ]:
max_profit_movie = df.iloc[df['profit'].idxmax()]
max_profit_movie

id                                                                    1762
belongs_to_collection    [{'id': 9485, 'name': 'The Fast and the Furiou...
budget                                                           190000000
genres                                      [{'id': 28, 'name': 'Action'}]
homepage                                          http://www.furious7.com/
imdb_id                                                          tt2820852
original_language                                                       en
original_title                                                   Furious 7
overview                 Deckard Shaw seeks revenge against Dominic Tor...
popularity                                                       27.275687
poster_path                               /dCgm7efXDmiABSdWDHBDBx2jwmn.jpg
production_companies     [{'name': 'Universal Pictures', 'id': 33}, {'n...
production_countries     [{'iso_3166_1': 'JP', 'name': 'Japan'}, {'iso_...
release_date                                                        4/1/15
runtime                                                              137.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                                                Vengeance Hits Home
title                                                            Furious 7
Keywords                 [{'id': 830, 'name': 'car race'}, {'id': 3428,...
cast                     [{'cast_id': 17, 'character': 'Dominic Toretto...
crew                     [{'credit_id': '52fe4cc8c3a36847f823e681', 'de...
revenue                                                         1506249360
profit                                                          1316249360
Name: 1761, dtype: object

In [ ]:
max_profit_movie['cast']

'[{\'cast_id\': 17, \'character\': \'Dominic Toretto\', \'credit_id\': \'5431dfd10e0a265915002c34\', \'gender\': 2, \'id\': 12835, \'name\': \'Vin Diesel\', \'order\': 0, \'profile_path\': \'/7rwSXluNWZAluYMOEWBxkPmckES.jpg\'}, {\'cast_id\': 19, \'character\': "Brian O\'Conner", \'credit_id\': \'5431dfe4c3a3681143002b98\', \'gender\': 2, \'id\': 8167, \'name\': \'Paul Walker\', \'order\': 1, \'profile_path\': \'/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg\'}, {\'cast_id\': 18, \'character\': \'Hobbs\', \'credit_id\': \'5431dfdbc3a36831a6004376\', \'gender\': 2, \'id\': 18918, \'name\': \'Dwayne Johnson\', \'order\': 2, \'profile_path\': \'/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg\'}, {\'cast_id\': 20, \'character\': \'Letty\', \'credit_id\': \'5431dfeec3a36811ef002c75\', \'gender\': 1, \'id\': 17647, \'name\': \'Michelle Rodriguez\', \'order\': 3, \'profile_path\': \'/v37VK0MNuRuJOCKPKJcZAJXRA5r.jpg\'}, {\'cast_id\': 28, \'character\': \'Roman\', \'credit_id\': \'5431e0310e0a2656e2002c95\', \'gender\': 2, \'id\': 8169, \'name\': \'Tyrese Gibson\', \'order\': 4, \'profile_path\': \'/a3tyF7QXgeEH0QuEuIzNZZ8oLNS.jpg\'}, {\'cast_id\': 31, \'character\': "Tej (as Chris \'Ludacris\' Bridges)", \'credit_id\': \'5431e0520e0a2658b2002c3c\', \'gender\': 2, \'id\': 8171, \'name\': \'Ludacris\', \'order\': 5, \'profile_path\': \'/xLfq9wFO6dtYuUK96hbJ8I8EKFw.jpg\'}, {\'cast_id\': 24, \'character\': \'Mia\', \'credit_id\': \'5431e00dc3a36811ef002c7e\', \'gender\': 1, \'id\': 22123, \'name\': \'Jordana Brewster\', \'order\': 6, \'profile_path\': \'/dORwXZWWmDgG66I5i2Fnr27g3fO.jpg\'}, {\'cast_id\': 25, \'character\': \'Jakande\', \'credit_id\': \'5431e015c3a36831a90040da\', \'gender\': 2, \'id\': 938, \'name\': \'Djimon Hounsou\', \'order\': 7, \'profile_path\': \'/y22Pb0XAVqC0l7ukzKKtXzPEuHk.jpg\'}, {\'cast_id\': 30, \'character\': \'Kiet\', \'credit_id\': \'5431e04a0e0a26464300432c\', \'gender\': 2, \'id\': 57207, \'name\': \'Tony Jaa\', \'order\': 8, \'profile_path\': \'/qq0uXKe3aKaAE04QQ0BvbbFFufF.jpg\'}, {\'cast_id\': 21, \'character\': \'Kara\', \'credit_id\': \'5431dff40e0a2646490043fa\', \'gender\': 0, \'id\': 997887, \'name\': \'Ronda Rousey\', \'order\': 9, \'profile_path\': \'/5eGHTV1bLOdajC4Z3pnIdSiptSG.jpg\'}, {\'cast_id\': 27, \'character\': \'Ramsey\', \'credit_id\': \'5431e026c3a36831ac004333\', \'gender\': 1, \'id\': 1251069, \'name\': \'Nathalie Emmanuel\', \'order\': 10, \'profile_path\': \'/yYiJwunH04doOZJgMu7qTZyrRYJ.jpg\'}, {\'cast_id\': 22, \'character\': \'Mr. Nobody\', \'credit_id\': \'5431dffa0e0a265872002bdf\', \'gender\': 2, \'id\': 6856, \'name\': \'Kurt Russell\', \'order\': 11, \'profile_path\': \'/rlnFuNkisPpuypARI7QaGCmOY6V.jpg\'}, {\'cast_id\': 16, \'character\': \'Deckard Shaw\', \'credit_id\': \'5431dfc70e0a265872002bd5\', \'gender\': 2, \'id\': 976, \'name\': \'Jason Statham\', \'order\': 12, \'profile_path\': \'/PhWiWgasncGWD9LdbsGcmxkV4r.jpg\'}, {\'cast_id\': 39, \'character\': \'Han\', \'credit_id\': \'554fa75f92514110bd002a7d\', \'gender\': 2, \'id\': 61697, \'name\': \'Sung Kang\', \'order\': 13, \'profile_path\': \'/fqt53KEfHWsRDcbV2YAY2lKlKrM.jpg\'}, {\'cast_id\': 38, \'character\': \'Gisele\', \'credit_id\': \'554fa7439251413e40005aa1\', \'gender\': 1, \'id\': 90633, \'name\': \'Gal Gadot\', \'order\': 14, \'profile_path\': \'/34kHAyBaBhq2kUrmhM15paEBuuI.jpg\'}, {\'cast_id\': 15, \'character\': \'Sean Boswell\', \'credit_id\': \'5431dfbb0e0a265915002c2d\', \'gender\': 2, \'id\': 155, \'name\': \'Lucas Black\', \'order\': 15, \'profile_path\': \'/41qZZc6vRVm5ZOoXWfEf5NGoIZR.jpg\'}, {\'cast_id\': 23, \'character\': \'Elena\', \'credit_id\': \'5431e003c3a36811ef002c7c\', \'gender\': 1, \'id\': 73269, \'name\': \'Elsa Pataky\', \'order\': 16, \'profile_path\': \'/c1km2kqasJT9GTISMbBZpp3jbuR.jpg\'}, {\'cast_id\': 35, \'character\': \'Hector\', \'credit_id\': \'554fa677c3a3687b7d002468\', \'gender\': 2, \'id\': 53252, \'name\': \'Noel Gugliemi\', \'order\': 17, \'profile_path\': \'/mI5urNyZJAzIGxelTjBkm624DkB.jpg\'}, {\'cast_id\': 37, \'character\': \'Sheppard\', \'credit_id\': \'554fa6f19251413ea10004fc\', \'gender\': 2, \'id\': 222906, \'name\': \'John Brotherton\', \'order\': 18, \'profile_path\': \'/sE73Zs4q8rugmrFnn9jv2wAEVrI.jpg\'}, {\'cast_id\': 34, \'character\': \'Owen Shaw\', \'credit_id\': \'554fa651c3a3681870005275\', \'gender\': 2, \'id\': 114019, \'name\': \'Luke Evans\', \'order\': 19, \'profile_path\': \'/1d31uDYub8TaLOPWfgX78OotduD.jpg\'}, {\'cast_id\': 36, \'character\': \'Safar\', \'credit_id\': \'554fa6d7c3a3685221000283\', \'gender\': 2, \'id\': 492791, \'name\': \'Ali Fazal\', \'order\': 20, \'profile_path\': \'/AmT132VCz3InJBAQQPJnqqgsQsB.jpg\'}, {\'cast_id\': 145, \'character\': \'Jack\', \'credit_id\': \'59a8b72092514157c601fb92\', \'gender\': 0, \'id\': 1880145, \'name\': \'Miller Kimsey\', \'order\': 21, \'profile_path\': None}, {\'cast_id\': 146, \'character\': \'Jack\', \'credit_id\': \'59a8b72b925141579d020797\', \'gender\': 0, \'id\': 1880146, \'name\': \'Charlie Kimsey\', \'order\': 22, \'profile_path\': None}, {\'cast_id\': 133, \'character\': \'Samantha Hobbs\', \'credit_id\': \'56417cfec3a3685be2001846\', \'gender\': 1, \'id\': 1533850, \'name\': \'Eden Estrella\', \'order\': 23, \'profile_path\': \'/xxzcCrgD38jOyCRlbBA5ksfrN14.jpg\'}, {\'cast_id\': 147, \'character\': \'Letty Fan\', \'credit_id\': \'59a8b787c3a36874d5007d12\', \'gender\': 2, \'id\': 1534800, \'name\': \'Gentry White\', \'order\': 24, \'profile_path\': \'/dzu9JUDSHDXrnit7ZlOnJuRJj1X.jpg\'}, {\'cast_id\': 26, \'character\': \'Female Racer\', \'credit_id\': \'5431e01c0e0a265834002c97\', \'gender\': 1, \'id\': 1364893, \'name\': \'Iggy Azalea\', \'order\': 25, \'profile_path\': \'/KG5skDx5WeGDijkUUQnmOP0crG.jpg\'}, {\'cast_id\': 148, \'character\': \'Male Racer\', \'credit_id\': \'59a8b7afc3a3683d0701b1ad\', \'gender\': 0, \'id\': 1161711, \'name\': \'Jon Lee Brody\', \'order\': 26, \'profile_path\': \'/u1agQE1nYgt2LOijksYJMPYxpKh.jpg\'}, {\'cast_id\': 135, \'character\': \'Race Starter\', \'credit_id\': \'56c259c89251414a9b000865\', \'gender\': 1, \'id\': 1578220, \'name\': \'Levy Tran\', \'order\': 27, \'profile_path\': \'/iKcRuLRwmcuoD43E4X0YlYquYGD.jpg\'}, {\'cast_id\': 132, \'character\': \'Hot Teacher\', \'credit_id\': \'56417cc592514128af001862\', \'gender\': 0, \'id\': 118593, \'name\': \'Anna Colwell\', \'order\': 28, \'profile_path\': \'/qerkK7Z26GttfJ8Sq6xMwhkYLq3.jpg\'}, {\'cast_id\': 149, \'character\': \'Doctor\', \'credit_id\': \'59a8b80e92514157ab0206fc\', \'gender\': 0, \'id\': 1880147, \'name\': \'Viktor Hernandez\', \'order\': 29, \'profile_path\': None}, {\'cast_id\': 150, \'character\': \'Priest\', \'credit_id\': \'59a8b84092514157c601fce8\', \'gender\': 2, \'id\': 80619, \'name\': \'Steve Coulter\', \'order\': 30, \'profile_path\': \'/v1cwS9Ia89pO154Wje3m4IxuI3.jpg\'}, {\'cast_id\': 130, \'character\': \'Merc Tech\', \'credit_id\': \'56417c3092514128a6001a15\', \'gender\': 0, \'id\': 97844, \'name\': \'Robert Pralgo\', \'order\': 31, \'profile_path\': \'/iDPgSaDVhwIItvqa2Wn79oaUzf8.jpg\'}, {\'cast_id\': 151, \'character\': \'Weapons Tech\', \'credit_id\': \'59a8b888c3a3683ce601e3aa\', \'gender\': 0, \'id\': 1381712, \'name\': \'Antwan Mills\', \'order\': 32, \'profile_path\': \'/58nvO2Se7TS0ETUEzHHjJ0MLH5U.jpg\'}, {\'cast_id\': 152, \'character\': \'Billionaire\', \'credit_id\': \'59a8b8bac3a36874d5007ea3\', \'gender\': 0, \'id\': 1880148, \'name\': \'J.J. Phillips\', \'order\': 33, \'profile_path\': None}, {\'cast_id\': 153, \'character\': \'Dominican Priest\', \'credit_id\': \'59a8b8ccc3a3683c8701fa73\', \'gender\': 0, \'id\': 1880149, \'name\': \'Jorge Ferragut\', \'order\': 34, \'profile_path\': None}, {\'cast_id\': 154, \'character\': \'Hana\', \'credit_id\': \'59a8b8e3c3a36874d5007ec7\', \'gender\': 0, \'id\': 1440699, \'name\': \'Sara Sohn\', \'order\': 35, \'profile_path\': \'/8nfPK3sFpHzw0uu66LmTK9HcQ5G.jpg\'}, {\'cast_id\': 155, \'character\': \'Merc Driver (as Ben Blankenship)\', \'credit_id\': \'59a8b904c3a3683c7a02381c\', \'gender\': 0, \'id\': 1093707, \'name\': \'Benjamin Blankenship\', \'order\': 36, \'profile_path\': \'/xl0O9d7xS6XGSRqQl16StOxtkOR.jpg\'}, {\'cast_id\': 156, \'character\': \'DJ\', \'credit_id\': \'59a8b953c3a36876710081c2\', \'gender\': 0, \'id\': 1880150, \'name\': \'D.J. Hapa\', \'order\': 37, \'profile_path\': None}, {\'cast_id\': 140, \'character\': \'DJ\', \'credit_id\': \'58eee68c92514142020018f0\', \'gender\': 0, \'id\': 224092, \'name\': \'T-Pain\', \'order\': 38, \'profile_path\': None}, {\'cast_id\': 157, \'character\': \'Drone Tech\', \'credit_id\': \'59a8b98892514157ee01f2d9\', \'gender\': 2, \'id\': 54792, \'name\': \'Brian Mahoney\', \'order\': 39, \'profile_path\': \'/v6pTsqgOHE5TldFV63Kr44idQNe.jpg\'}, {\'cast_id\': 131, \'character\': \'Jasmine\', \'credit_id\': \'56417c7b92514128a90018fb\', \'gender\': 1, \'id\': 1128522, \'name\': \'Brittney Alger\', \'order\': 40, \'profile_path\': \'/u1eKIGLkK2GTpqFArNxgAMTMhOj.jpg\'}, {\'cast_id\': 158, \'character\': \'Mando\', \'credit_id\': \'59a8b9ad92514157ab020902\', \'gender\': 0, \'id\': 1451616, \'name\': \'Romeo Santos\', \'order\': 41, \'profile_path\': \'/lbt98DkUpRNoJXiFbXzQfhMIRt4.jpg\'}, {\'cast_id\': 159, \'character\': \'Advisor\', \'credit_id\': \'59a8b9ca925141579d020ab6\', \'gender\': 1, \'id\': 78804, \'name\': \'Jocelin Donahue\', \'order\': 42, \'profile_path\': \'/eQXBzPjo9K8MG9TVOoQDNoHEFwv.jpg\'}, {\'cast_id\': 160, \'character\': \'Field Reporter\', \'credit_id\': \'59a8b9da9251415808021296\', \'gender\': 0, \'id\': 1880151, \'name\': \'Stephanie Langston\', \'order\': 43, \'profile_path\': None}, {\'cast_id\': 161, \'character\': \'Cop\', \'credit_id\': \'59a8b9f192514157a5020874\', \'gender\': 0, \'id\': 1448173, \'name\': \'Jorge-Luis Pallo\', \'order\': 44, \'profile_path\': \'/9cw97jnvm7SvnCTNBWZHXt4clfu.jpg\'}, {\'cast_id\': 143, \'character\': \'Leo (uncredited / archive)\', \'credit_id\': \'58eee6b8925141423500180f\', \'gender\': 2, \'id\': 96321, \'name\': \'Tego Calder√≥n\', \'order\': 45, \'profile_path\': \'/pz7i7LV35XRC5Si8liRoYWdrcr0.jpg\'}, {\'cast_id\': 142, \'character\': \'Neela (uncredited / archive)\', \'credit_id\': \'58eee6ab92514141ff001971\', \'gender\': 1, \'id\': 116277, \'name\': \'Nathalie Kelley\', \'order\': 46, \'profile_path\': \'/68xBLk7FvQ36v794LbOrMxeOJeQ.jpg\'}, {\'cast_id\': 29, \'character\': \'Twinkie (uncredited)\', \'credit_id\': \'5431e03e0e0a265872002bf2\', \'gender\': 0, \'id\': 58197, \'name\': \'Shad Moss\', \'order\': 47, \'profile_path\': \'/A1rHY9B5R9cIQshClcJxBYINg1m.jpg\'}, {\'cast_id\': 144, \'character\': \'Santos (uncredited / archive)\', \'credit_id\': \'58eee6c492514141f70019b8\', \'gender\': 0, \'id\': 90634, \'name\': \'Don Omar\', \'order\': 48, \'profile_path\': \'/f1INIG2TE9jXXp5A3gGJR9UkePK.jpg\'}, {\'cast_id\': 141, \'character\': \'Race Wars Racer (uncredited)\', \'credit_id\': \'58eee698c3a36826510017dc\', \'gender\': 0, \'id\': 1563213, \'name\': \'Klement Tinaj\', \'order\': 49, \'profile_path\': None}, {\'cast_id\': 139, \'character\': "Brian O\'Conner (uncredited)", \'credit_id\': \'58eee621c3a368265e001729\', \'gender\': 0, \'id\': 1795034, \'name\': \'Caleb Walker\', \'order\': 50, \'profile_path\': None}, {\'cast_id\': 45, \'character\': "Brian O\'Connor (uncredited)", \'credit_id\': \'5589e3fd925141569c00003e\', \'gender\': 2, \'id\': 1480862, \'name\': \'Cody Walker\', \'order\': 51, \'profile_path\': \'/6InC9qPrftOqsRK9ALcKFLHXSLV.jpg\'}]'

In [ ]:
eval(max_profit_movie['cast'])

[{'cast_id': 17,
  'character': 'Dominic Toretto',
  'credit_id': '5431dfd10e0a265915002c34',
  'gender': 2,
  'id': 12835,
  'name': 'Vin Diesel',
  'order': 0,
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'cast_id': 19,
  'character': "Brian O'Conner",
  'credit_id': '5431dfe4c3a3681143002b98',
  'gender': 2,
  'id': 8167,
  'name': 'Paul Walker',
  'order': 1,
  'profile_path': '/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg'},
 {'cast_id': 18,
  'character': 'Hobbs',
  'credit_id': '5431dfdbc3a36831a6004376',
  'gender': 2,
  'id': 18918,
  'name': 'Dwayne Johnson',
  'order': 2,
  'profile_path': '/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg'},
 {'cast_id': 20,
  'character': 'Letty',
  'credit_id': '5431dfeec3a36811ef002c75',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 3,
  'profile_path': '/v37VK0MNuRuJOCKPKJcZAJXRA5r.jpg'},
 {'cast_id': 28,
  'character': 'Roman',
  'credit_id': '5431e0310e0a2656e2002c95',
  'gender': 2,
  'id': 8169,
  'name': 'Tyrese Gibson',
  'order': 4,
  'profile_path': '/a3tyF7QXgeEH0QuEuIzNZZ8oLNS.jpg'},
 {'cast_id': 31,
  'character': "Tej (as Chris 'Ludacris' Bridges)",
  'credit_id': '5431e0520e0a2658b2002c3c',
  'gender': 2,
  'id': 8171,
  'name': 'Ludacris',
  'order': 5,
  'profile_path': '/xLfq9wFO6dtYuUK96hbJ8I8EKFw.jpg'},
 {'cast_id': 24,
  'character': 'Mia',
  'credit_id': '5431e00dc3a36811ef002c7e',
  'gender': 1,
  'id': 22123,
  'name': 'Jordana Brewster',
  'order': 6,
  'profile_path': '/dORwXZWWmDgG66I5i2Fnr27g3fO.jpg'},
 {'cast_id': 25,
  'character': 'Jakande',
  'credit_id': '5431e015c3a36831a90040da',
  'gender': 2,
  'id': 938,
  'name': 'Djimon Hounsou',
  'order': 7,
  'profile_path': '/y22Pb0XAVqC0l7ukzKKtXzPEuHk.jpg'},
 {'cast_id': 30,
  'character': 'Kiet',
  'credit_id': '5431e04a0e0a26464300432c',
  'gender': 2,
  'id': 57207,
  'name': 'Tony Jaa',
  'order': 8,
  'profile_path': '/qq0uXKe3aKaAE04QQ0BvbbFFufF.jpg'},
 {'cast_id': 21,
  'character': 'Kara',
  'credit_id': '5431dff40e0a2646490043fa',
  'gender': 0,
  'id': 997887,
  'name': 'Ronda Rousey',
  'order': 9,
  'profile_path': '/5eGHTV1bLOdajC4Z3pnIdSiptSG.jpg'},
 {'cast_id': 27,
  'character': 'Ramsey',
  'credit_id': '5431e026c3a36831ac004333',
  'gender': 1,
  'id': 1251069,
  'name': 'Nathalie Emmanuel',
  'order': 10,
  'profile_path': '/yYiJwunH04doOZJgMu7qTZyrRYJ.jpg'},
 {'cast_id': 22,
  'character': 'Mr. Nobody',
  'credit_id': '5431dffa0e0a265872002bdf',
  'gender': 2,
  'id': 6856,
  'name': 'Kurt Russell',
  'order': 11,
  'profile_path': '/rlnFuNkisPpuypARI7QaGCmOY6V.jpg'},
 {'cast_id': 16,
  'character': 'Deckard Shaw',
  'credit_id': '5431dfc70e0a265872002bd5',
  'gender': 2,
  'id': 976,
  'name': 'Jason Statham',
  'order': 12,
  'profile_path': '/PhWiWgasncGWD9LdbsGcmxkV4r.jpg'},
 {'cast_id': 39,
  'character': 'Han',
  'credit_id': '554fa75f92514110bd002a7d',
  'gender': 2,
  'id': 61697,
  'name': 'Sung Kang',
  'order': 13,
  'profile_path': '/fqt53KEfHWsRDcbV2YAY2lKlKrM.jpg'},
 {'cast_id': 38,
  'character': 'Gisele',
  'credit_id': '554fa7439251413e40005aa1',
  'gender': 1,
  'id': 90633,
  'name': 'Gal Gadot',
  'order': 14,
  'profile_path': '/34kHAyBaBhq2kUrmhM15paEBuuI.jpg'},
 {'cast_id': 15,
  'character': 'Sean Boswell',
  'credit_id': '5431dfbb0e0a265915002c2d',
  'gender': 2,
  'id': 155,
  'name': 'Lucas Black',
  'order': 15,
  'profile_path': '/41qZZc6vRVm5ZOoXWfEf5NGoIZR.jpg'},
 {'cast_id': 23,
  'character': 'Elena',
  'credit_id': '5431e003c3a36811ef002c7c',
  'gender': 1,
  'id': 73269,
  'name': 'Elsa Pataky',
  'order': 16,
  'profile_path': '/c1km2kqasJT9GTISMbBZpp3jbuR.jpg'},
 {'cast_id': 35,
  'character': 'Hector',
  'credit_id': '554fa677c3a3687b7d002468',
  'gender': 2,
  'id': 53252,
  'name': 'Noel Gugliemi',
  'order': 17,
  'profile_path': '/mI5urNyZJAzIGxelTjBkm624DkB.jpg'},
 {'cast_id': 37,
  'character': 'Sheppard',
  'credit_id': '554fa6f19251413ea10004fc',
  'gender': 2,
  'id': 222906,
  'name': 'John Brotherton',
  'order': 18,
  'profile_path': '/sE73Zs4q8rugmrFnn9jv2wAEVrI.jpg'},
 {'cast_id': 34,
  'character': 'Owen Shaw',
  'credit_id': '554fa651c3a3681870005275',
  'gender': 2,
  'id': 114019,
  'name': 'Luke Evans',
  'order': 19,
  'profile_path': '/1d31uDYub8TaLOPWfgX78OotduD.jpg'},
 {'cast_id': 36,
  'character': 'Safar',
  'credit_id': '554fa6d7c3a3685221000283',
  'gender': 2,
  'id': 492791,
  'name': 'Ali Fazal',
  'order': 20,
  'profile_path': '/AmT132VCz3InJBAQQPJnqqgsQsB.jpg'},
 {'cast_id': 145,
  'character': 'Jack',
  'credit_id': '59a8b72092514157c601fb92',
  'gender': 0,
  'id': 1880145,
  'name': 'Miller Kimsey',
  'order': 21,
  'profile_path': None},
 {'cast_id': 146,
  'character': 'Jack',
  'credit_id': '59a8b72b925141579d020797',
  'gender': 0,
  'id': 1880146,
  'name': 'Charlie Kimsey',
  'order': 22,
  'profile_path': None},
 {'cast_id': 133,
  'character': 'Samantha Hobbs',
  'credit_id': '56417cfec3a3685be2001846',
  'gender': 1,
  'id': 1533850,
  'name': 'Eden Estrella',
  'order': 23,
  'profile_path': '/xxzcCrgD38jOyCRlbBA5ksfrN14.jpg'},
 {'cast_id': 147,
  'character': 'Letty Fan',
  'credit_id': '59a8b787c3a36874d5007d12',
  'gender': 2,
  'id': 1534800,
  'name': 'Gentry White',
  'order': 24,
  'profile_path': '/dzu9JUDSHDXrnit7ZlOnJuRJj1X.jpg'},
 {'cast_id': 26,
  'character': 'Female Racer',
  'credit_id': '5431e01c0e0a265834002c97',
  'gender': 1,
  'id': 1364893,
  'name': 'Iggy Azalea',
  'order': 25,
  'profile_path': '/KG5skDx5WeGDijkUUQnmOP0crG.jpg'},
 {'cast_id': 148,
  'character': 'Male Racer',
  'credit_id': '59a8b7afc3a3683d0701b1ad',
  'gender': 0,
  'id': 1161711,
  'name': 'Jon Lee Brody',
  'order': 26,
  'profile_path': '/u1agQE1nYgt2LOijksYJMPYxpKh.jpg'},
 {'cast_id': 135,
  'character': 'Race Starter',
  'credit_id': '56c259c89251414a9b000865',
  'gender': 1,
  'id': 1578220,
  'name': 'Levy Tran',
  'order': 27,
  'profile_path': '/iKcRuLRwmcuoD43E4X0YlYquYGD.jpg'},
 {'cast_id': 132,
  'character': 'Hot Teacher',
  'credit_id': '56417cc592514128af001862',
  'gender': 0,
  'id': 118593,
  'name': 'Anna Colwell',
  'order': 28,
  'profile_path': '/qerkK7Z26GttfJ8Sq6xMwhkYLq3.jpg'},
 {'cast_id': 149,
  'character': 'Doctor',
  'credit_id': '59a8b80e92514157ab0206fc',
  'gender': 0,
  'id': 1880147,
  'name': 'Viktor Hernandez',
  'order': 29,
  'profile_path': None},
 {'cast_id': 150,
  'character': 'Priest',
  'credit_id': '59a8b84092514157c601fce8',
  'gender': 2,
  'id': 80619,
  'name': 'Steve Coulter',
  'order': 30,
  'profile_path': '/v1cwS9Ia89pO154Wje3m4IxuI3.jpg'},
 {'cast_id': 130,
  'character': 'Merc Tech',
  'credit_id': '56417c3092514128a6001a15',
  'gender': 0,
  'id': 97844,
  'name': 'Robert Pralgo',
  'order': 31,
  'profile_path': '/iDPgSaDVhwIItvqa2Wn79oaUzf8.jpg'},
 {'cast_id': 151,
  'character': 'Weapons Tech',
  'credit_id': '59a8b888c3a3683ce601e3aa',
  'gender': 0,
  'id': 1381712,
  'name': 'Antwan Mills',
  'order': 32,
  'profile_path': '/58nvO2Se7TS0ETUEzHHjJ0MLH5U.jpg'},
 {'cast_id': 152,
  'character': 'Billionaire',
  'credit_id': '59a8b8bac3a36874d5007ea3',
  'gender': 0,
  'id': 1880148,
  'name': 'J.J. Phillips',
  'order': 33,
  'profile_path': None},
 {'cast_id': 153,
  'character': 'Dominican Priest',
  'credit_id': '59a8b8ccc3a3683c8701fa73',
  'gender': 0,
  'id': 1880149,
  'name': 'Jorge Ferragut',
  'order': 34,
  'profile_path': None},
 {'cast_id': 154,
  'character': 'Hana',
  'credit_id': '59a8b8e3c3a36874d5007ec7',
  'gender': 0,
  'id': 1440699,
  'name': 'Sara Sohn',
  'order': 35,
  'profile_path': '/8nfPK3sFpHzw0uu66LmTK9HcQ5G.jpg'},
 {'cast_id': 155,
  'character': 'Merc Driver (as Ben Blankenship)',
  'credit_id': '59a8b904c3a3683c7a02381c',
  'gender': 0,
  'id': 1093707,
  'name': 'Benjamin Blankenship',
  'order': 36,
  'profile_path': '/xl0O9d7xS6XGSRqQl16StOxtkOR.jpg'},
 {'cast_id': 156,
  'character': 'DJ',
  'credit_id': '59a8b953c3a36876710081c2',
  'gender': 0,
  'id': 1880150,
  'name': 'D.J. Hapa',
  'order': 37,
  'profile_path': None},
 {'cast_id': 140,
  'character': 'DJ',
  'credit_id': '58eee68c92514142020018f0',
  'gender': 0,
  'id': 224092,
  'name': 'T-Pain',
  'order': 38,
  'profile_path': None},
 {'cast_id': 157,
  'character': 'Drone Tech',
  'credit_id': '59a8b98892514157ee01f2d9',
  'gender': 2,
  'id': 54792,
  'name': 'Brian Mahoney',
  'order': 39,
  'profile_path': '/v6pTsqgOHE5TldFV63Kr44idQNe.jpg'},
 {'cast_id': 131,
  'character': 'Jasmine',
  'credit_id': '56417c7b92514128a90018fb',
  'gender': 1,
  'id': 1128522,
  'name': 'Brittney Alger',
  'order': 40,
  'profile_path': '/u1eKIGLkK2GTpqFArNxgAMTMhOj.jpg'},
 {'cast_id': 158,
  'character': 'Mando',
  'credit_id': '59a8b9ad92514157ab020902',
  'gender': 0,
  'id': 1451616,
  'name': 'Romeo Santos',
  'order': 41,
  'profile_path': '/lbt98DkUpRNoJXiFbXzQfhMIRt4.jpg'},
 {'cast_id': 159,
  'character': 'Advisor',
  'credit_id': '59a8b9ca925141579d020ab6',
  'gender': 1,
  'id': 78804,
  'name': 'Jocelin Donahue',
  'order': 42,
  'profile_path': '/eQXBzPjo9K8MG9TVOoQDNoHEFwv.jpg'},
 {'cast_id': 160,
  'character': 'Field Reporter',
  'credit_id': '59a8b9da9251415808021296',
  'gender': 0,
  'id': 1880151,
  'name': 'Stephanie Langston',
  'order': 43,
  'profile_path': None},
 {'cast_id': 161,
  'character': 'Cop',
  'credit_id': '59a8b9f192514157a5020874',
  'gender': 0,
  'id': 1448173,
  'name': 'Jorge-Luis Pallo',
  'order': 44,
  'profile_path': '/9cw97jnvm7SvnCTNBWZHXt4clfu.jpg'},
 {'cast_id': 143,
  'character': 'Leo (uncredited / archive)',
  'credit_id': '58eee6b8925141423500180f',
  'gender': 2,
  'id': 96321,
  'name': 'Tego Calder√≥n',
  'order': 45,
  'profile_path': '/pz7i7LV35XRC5Si8liRoYWdrcr0.jpg'},
 {'cast_id': 142,
  'character': 'Neela (uncredited / archive)',
  'credit_id': '58eee6ab92514141ff001971',
  'gender': 1,
  'id': 116277,
  'name': 'Nathalie Kelley',
  'order': 46,
  'profile_path': '/68xBLk7FvQ36v794LbOrMxeOJeQ.jpg'},
 {'cast_id': 29,
  'character': 'Twinkie (uncredited)',
  'credit_id': '5431e03e0e0a265872002bf2',
  'gender': 0,
  'id': 58197,
  'name': 'Shad Moss',
  'order': 47,
  'profile_path': '/A1rHY9B5R9cIQshClcJxBYINg1m.jpg'},
 {'cast_id': 144,
  'character': 'Santos (uncredited / archive)',
  'credit_id': '58eee6c492514141f70019b8',
  'gender': 0,
  'id': 90634,
  'name': 'Don Omar',
  'order': 48,
  'profile_path': '/f1INIG2TE9jXXp5A3gGJR9UkePK.jpg'},
 {'cast_id': 141,
  'character': 'Race Wars Racer (uncredited)',
  'credit_id': '58eee698c3a36826510017dc',
  'gender': 0,
  'id': 1563213,
  'name': 'Klement Tinaj',
  'order': 49,
  'profile_path': None},
 {'cast_id': 139,
  'character': "Brian O'Conner (uncredited)",
  'credit_id': '58eee621c3a368265e001729',
  'gender': 0,
  'id': 1795034,
  'name': 'Caleb Walker',
  'order': 50,
  'profile_path': None},
 {'cast_id': 45,
  'character': "Brian O'Connor (uncredited)",
  'credit_id': '5589e3fd925141569c00003e',
  'gender': 2,
  'id': 1480862,
  'name': 'Cody Walker',
  'order': 51,
  'profile_path': '/6InC9qPrftOqsRK9ALcKFLHXSLV.jpg'}]

In [ ]:
actor_name = []
for i in eval(max_profit_movie['cast']):
  actor_name.append(i['name'])

print(actor_name)

['Vin Diesel', 'Paul Walker', 'Dwayne Johnson', 'Michelle Rodriguez', 'Tyrese Gibson', 'Ludacris', 'Jordana Brewster', 'Djimon Hounsou', 'Tony Jaa', 'Ronda Rousey', 'Nathalie Emmanuel', 'Kurt Russell', 'Jason Statham', 'Sung Kang', 'Gal Gadot', 'Lucas Black', 'Elsa Pataky', 'Noel Gugliemi', 'John Brotherton', 'Luke Evans', 'Ali Fazal', 'Miller Kimsey', 'Charlie Kimsey', 'Eden Estrella', 'Gentry White', 'Iggy Azalea', 'Jon Lee Brody', 'Levy Tran', 'Anna Colwell', 'Viktor Hernandez', 'Steve Coulter', 'Robert Pralgo', 'Antwan Mills', 'J.J. Phillips', 'Jorge Ferragut', 'Sara Sohn', 'Benjamin Blankenship', 'D.J. Hapa', 'T-Pain', 'Brian Mahoney', 'Brittney Alger', 'Romeo Santos', 'Jocelin Donahue', 'Stephanie Langston', 'Jorge-Luis Pallo', 'Tego Calder√≥n', 'Nathalie Kelley', 'Shad Moss', 'Don Omar', 'Klement Tinaj', 'Caleb Walker', 'Cody Walker']

In [ ]:
max_profit_movie['crew']

'[{\'credit_id\': \'52fe4cc8c3a36847f823e681\', \'department\': \'Production\', \'gender\': 2, \'id\': 12835, \'job\': \'Producer\', \'name\': \'Vin Diesel\', \'profile_path\': \'/7rwSXluNWZAluYMOEWBxkPmckES.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e687\', \'department\': \'Production\', \'gender\': 2, \'id\': 11874, \'job\': \'Producer\', \'name\': \'Neal H. Moritz\', \'profile_path\': \'/cNcsEYmoS4niCz3UkVAA09dUIob.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e68d\', \'department\': \'Writing\', \'gender\': 2, \'id\': 58191, \'job\': \'Writer\', \'name\': \'Chris Morgan\', \'profile_path\': \'/dUGxIwFBLrSFLImxjeda1krndMO.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e693\', \'department\': \'Writing\', \'gender\': 0, \'id\': 8162, \'job\': \'Characters\', \'name\': \'Gary Scott Thompson\', \'profile_path\': \'/e2dMfqFvRsOXgWZ1VToYLmos17y.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e699\', \'department\': \'Directing\', \'gender\': 2, \'id\': 2127, \'job\': \'Director\', \'name\': \'James Wan\', \'profile_path\': \'/d1LSKfzi5J6QngWS7niN1zPJdud.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e6a7\', \'department\': \'Camera\', \'gender\': 2, \'id\': 58192, \'job\': \'Director of Photography\', \'name\': \'Stephen F. Windon\', \'profile_path\': None}, {\'credit_id\': \'5534714692514125dc002be4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1455610, \'job\': \'Animation\', \'name\': \'Tony Mecca\', \'profile_path\': None}, {\'credit_id\': \'554fa7b992514110bd002a9d\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1421687, \'job\': \'Director of Photography\', \'name\': \'Marc Spicer\', \'profile_path\': None}, {\'credit_id\': \'554fa7cbc3a36822540047fd\', \'department\': \'Production\', \'gender\': 1, \'id\': 90635, \'job\': \'Executive Producer\', \'name\': \'Samantha Vincent\', \'profile_path\': None}, {\'credit_id\': \'554fa7d89251413fcf00773d\', \'department\': \'Production\', \'gender\': 0, \'id\': 84064, \'job\': \'Associate Producer\', \'name\': \'F. Valentino Morales\', \'profile_path\': \'/w85eCnNP0VgmfV5NWyq2SvRGi2y.jpg\'}, {\'credit_id\': \'554fa7f2c3a3682254004803\', \'department\': \'Production\', \'gender\': 2, \'id\': 8181, \'job\': \'Producer\', \'name\': \'Michael Fottrell\', \'profile_path\': None}, {\'credit_id\': \'554fa80292514110bd002aa8\', \'department\': \'Production\', \'gender\': 0, \'id\': 75826, \'job\': \'Producer\', \'name\': \'Brandon Birtell\', \'profile_path\': None}, {\'credit_id\': \'55ed993ac3a3682c62015607\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1204244, \'job\': \'Editor\', \'name\': \'Leigh Folsom Boyd\', \'profile_path\': None}, {\'credit_id\': \'55ed994cc3a3687d3b00d64c\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1204245, \'job\': \'Editor\', \'name\': \'Dylan Highsmith\', \'profile_path\': None}, {\'credit_id\': \'55ed995dc3a3682c5d016867\', \'department\': \'Editing\', \'gender\': 0, \'id\': 62813, \'job\': \'Editor\', \'name\': \'Kirk M. Morri\', \'profile_path\': None}, {\'credit_id\': \'55ed99739251413e41014641\', \'department\': \'Editing\', \'gender\': 2, \'id\': 6668, \'job\': \'Editor\', \'name\': \'Christian Wagner\', \'profile_path\': None}, {\'credit_id\': \'55ed99859251413e3a014aae\', \'department\': \'Production\', \'gender\': 1, \'id\': 9545, \'job\': \'Casting\', \'name\': \'Anne McCarthy\', \'profile_path\': None}, {\'credit_id\': \'55ed99a4c3a3682c5d016875\', \'department\': \'Production\', \'gender\': 0, \'id\': 1276602, \'job\': \'Casting\', \'name\': \'Kellie Roy\', \'profile_path\': None}, {\'credit_id\': \'55ed99c7c3a3682c5d01687e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1445830, \'job\': \'Art Direction\', \'name\': \'Jonathan Carlos\', \'profile_path\': None}, {\'credit_id\': \'55ed99d89251413e32014a65\', \'department\': \'Art\', \'gender\': 2, \'id\': 62780, \'job\': \'Art Direction\', \'name\': \'Alan Hook\', \'profile_path\': None}, {\'credit_id\': \'55ed99e992514106d600d85e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1493864, \'job\': \'Art Direction\', \'name\': \'Jay Pelissier\', \'profile_path\': None}, {\'credit_id\': \'55ed9a36c3a3682c700147e3\', \'department\': \'Art\', \'gender\': 1, \'id\': 1506359, \'job\': \'Art Department Coordinator\', \'name\': \'Kelly Richardson\', \'profile_path\': None}, {\'credit_id\': \'55ed9a52c3a3682c640130c3\', \'department\': \'Art\', \'gender\': 0, \'id\': 1506360, \'job\': \'Art Department Coordinator\', \'name\': \'Courtney Cocherell\', \'profile_path\': None}, {\'credit_id\': \'55ed9a6cc3a368090c004f9c\', \'department\': \'Art\', \'gender\': 0, \'id\': 1326651, \'job\': \'Assistant Art Director\', \'name\': \'Elena Albanese\', \'profile_path\': None}, {\'credit_id\': \'55ed9a96c3a3686f17003be1\', \'department\': \'Art\', \'gender\': 0, \'id\': 1405376, \'job\': \'Assistant Art Director\', \'name\': \'Alex McCarroll\', \'profile_path\': None}, {\'credit_id\': \'55ed9acbc3a3682c640130e4\', \'department\': \'Art\', \'gender\': 0, \'id\': 1338147, \'job\': \'Construction Coordinator\', \'name\': \'Bruce Di Valerio\', \'profile_path\': None}, {\'credit_id\': \'55ed9b03c3a3682c640130f5\', \'department\': \'Art\', \'gender\': 2, \'id\': 52600, \'job\': \'Production Design\', \'name\': \'Bill Brzeski\', \'profile_path\': None}, {\'credit_id\': \'55ed9b169251413e2f0145a8\', \'department\': \'Art\', \'gender\': 1, \'id\': 75391, \'job\': \'Set Decoration\', \'name\': \'Danielle Berman\', \'profile_path\': None}, {\'credit_id\': \'55ed9b29c3a3682c5d0168d9\', \'department\': \'Costume & Make-Up\', \'gender\': 1, \'id\': 2519, \'job\': \'Costume Design\', \'name\': \'Sanja Milkovic Hays\', \'profile_path\': None}, {\'credit_id\': \'55ed9bdac3a3682c62015698\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1439109, \'job\': \'Costume Supervisor\', \'name\': \'Nava R. Sadan\', \'profile_path\': None}, {\'credit_id\': \'55ed9c0bc3a3686f17003c45\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1439747, \'job\': \'Costume Supervisor\', \'name\': \'Andrew Hunt\', \'profile_path\': None}, {\'credit_id\': \'55ed9c3192514106d600d8e0\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506364, \'job\': \'Set Costumer\', \'name\': \'Jim Alan Cook\', \'profile_path\': None}, {\'credit_id\': \'55ed9c45c3a3682c5d016925\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1415019, \'job\': \'Set Costumer\', \'name\': \'Shayne Allen Duhon\', \'profile_path\': None}, {\'credit_id\': \'55ed9c579251413e32014af5\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506365, \'job\': \'Set Costumer\', \'name\': \'Empress Holley\', \'profile_path\': None}, {\'credit_id\': \'55ed9c6d9251413e450148ff\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1413125, \'job\': \'Set Costumer\', \'name\': \'Marina Marit\', \'profile_path\': None}, {\'credit_id\': \'55ed9c8d92514106d600d8fb\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506366, \'job\': \'Set Costumer\', \'name\': \'Les Morgan\', \'profile_path\': None}, {\'credit_id\': \'55ed9cda9251413e2f014612\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1408293, \'job\': \'Hairstylist\', \'name\': \'Linda D. Flowers\', \'profile_path\': None}, {\'credit_id\': \'55ed9cf69251413e2f01461d\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1412767, \'job\': \'Hairstylist\', \'name\': "Yesim \'Shimmy\' Osman", \'profile_path\': None}, {\'credit_id\': \'55ed9d0ec3a3687d3b00d73a\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506367, \'job\': \'Hairstylist\', \'name\': \'Jennifer Santiago\', \'profile_path\': None}, {\'credit_id\': \'55ed9d2a9251413e3e0155d8\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1425409, \'job\': \'Hairstylist\', \'name\': \'Rachel Solow\', \'profile_path\': None}, {\'credit_id\': \'55ed9d4cc3a3682c620156ed\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1452643, \'job\': \'Hairstylist\', \'name\': \'Roxane Griffin\', \'profile_path\': None}, {\'credit_id\': \'55ed9d6fc3a3682c5d01696f\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1309209, \'job\': \'Makeup Department Head\', \'name\': \'James MacKinnon\', \'profile_path\': None}, {\'credit_id\': \'55ed9d8cc3a368090c00504f\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506368, \'job\': \'Makeup Artist\', \'name\': \'Autumn Butler\', \'profile_path\': None}, {\'credit_id\': \'55ed9da09251413e3a014b98\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1437798, \'job\': \'Makeup Artist\', \'name\': "Roxy D\'Alonzo", \'profile_path\': None}, {\'credit_id\': \'55ed9db79251413e3a014ba5\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506369, \'job\': \'Makeup Artist\', \'name\': \'Hee Soo Kwon\', \'profile_path\': None}, {\'credit_id\': \'55ed9dce9251413e32014b4e\', \'department\': \'Costume & Make-Up\', \'gender\': 1, \'id\': 1459196, \'job\': \'Makeup Artist\', \'name\': \'Sarah Mays\', \'profile_path\': None}, {\'credit_id\': \'55ed9de4c3a3687d3b00d775\', \'department\': \'Costume & Make-Up\', \'gender\': 2, \'id\': 15330, \'job\': \'Makeup Artist\', \'name\': \'Paul Pattison\', \'profile_path\': None}, {\'credit_id\': \'55ed9df99251413e3e015610\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1317667, \'job\': \'Makeup Artist\', \'name\': \'Eleanor Sabaduquia\', \'profile_path\': None}, {\'credit_id\': \'55ed9e1fc3a3687d3b00d77e\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1414497, \'job\': \'Property Master\', \'name\': \'Guillaume DeLouche\', \'profile_path\': None}, {\'credit_id\': \'55ed9e3ac3a368090c005084\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1464516, \'job\': \'Property Master\', \'name\': \'Douglas T. Madison\', \'profile_path\': None}, {\'credit_id\': \'55ed9f5d9251413e3e015662\', \'department\': \'Crew\', \'gender\': 2, \'id\': 57158, \'job\': \'Second Unit Cinematographer\', \'name\': \'Igor Meglic\', \'profile_path\': None}, {\'credit_id\': \'55ed9fa0c3a3682c6401320f\', \'department\': \'Crew\', \'gender\': 0, \'id\': 13670, \'job\': \'Second Unit Cinematographer\', \'name\': \'Jacques Haitkin\', \'profile_path\': None}, {\'credit_id\': \'55ed9fc59251413e32014bbc\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1437304, \'job\': \'Gaffer\', \'name\': \'Michael Ambrose\', \'profile_path\': None}, {\'credit_id\': \'55ed9fe79251413e410147e4\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1506371, \'job\': \'Camera Operator\', \'name\': \'Denise Bailie\', \'profile_path\': None}, {\'credit_id\': \'55ed9ffa9251413e3a014c40\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1506373, \'job\': \'Camera Operator\', \'name\': \'Robert-James Bova\', \'profile_path\': None}, {\'credit_id\': \'55eda0299251413e3a014c49\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1439108, \'job\': \'Rigging Gaffer\', \'name\': \'Tom Fendley\', \'profile_path\': None}, {\'credit_id\': \'55eda056c3a3682c7001494b\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1434896, \'job\': \'Camera Operator\', \'name\': \'Sarah Levy\', \'profile_path\': None}, {\'credit_id\': \'55eda06e9251413e450149ee\', \'department\': \'Camera\', \'gender\': 2, \'id\': 74989, \'job\': \'Camera Operator\', \'name\': \'Mark Emery Moore\', \'profile_path\': \'/mhjX0FuAXv6SeSLLFHpaaiQbx6P.jpg\'}, {\'credit_id\': \'55eda082c3a3682c6b014009\', \'department\': \'Camera\', \'gender\': 2, \'id\': 1432918, \'job\': \'Camera Operator\', \'name\': \'Daniel Nichols\', \'profile_path\': None}, {\'credit_id\': \'55eda09d9251413e3e01569d\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1439104, \'job\': \'Camera Operator\', \'name\': \'Onofrio Nino Pansini\', \'profile_path\': None}, {\'credit_id\': \'55eda0b59251413e3a014c6c\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1408356, \'job\': \'Camera Operator\', \'name\': \'David Richert\', \'profile_path\': None}, {\'credit_id\': \'55eda0d1c3a3686f17003d58\', \'department\': \'Camera\', \'gender\': 2, \'id\': 1411271, \'job\': \'Camera Operator\', \'name\': \'Michael J. Walker\', \'profile_path\': None}, {\'credit_id\': \'55eda0f7c3a3687d3b00d81b\', \'department\': \'Camera\', \'gender\': 2, \'id\': 1378241, \'job\': \'Camera Operator\', \'name\': \'Maurice K. McGuire\', \'profile_path\': None}, {\'credit_id\': \'55eda1159251413e3e0156bd\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1411842, \'job\': \'Camera Operator\', \'name\': \'Richard Latham\', \'profile_path\': None}, {\'credit_id\': \'55eda12c92514106d600da0a\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1404739, \'job\': \'Helicopter Camera\', \'name\': \'Steve Koster\', \'profile_path\': None}, {\'credit_id\': \'55eda1939251413e3501498d\', \'department\': \'Camera\', \'gender\': 0, \'id\': 91122, \'job\': \'Helicopter Camera\', \'name\': \'Dylan Goss\', \'profile_path\': None}, {\'credit_id\': \'55eda1b39251413e3a014ca8\', \'department\': \'Camera\', \'gender\': 0, \'id\': 82169, \'job\': \'Steadicam Operator\', \'name\': \'Geoffrey Haley\', \'profile_path\': None}, {\'credit_id\': \'55eda1c7c3a3686f17003d8c\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1419105, \'job\': \'Still Photographer\', \'name\': \'Scott Garfield\', \'profile_path\': None}, {\'credit_id\': \'55eda1dbc3a3686f17003d92\', \'department\': \'Camera\', \'gender\': 2, \'id\': 1395281, \'job\': \'Additional Camera\', \'name\': \'Bob Gorelick\', \'profile_path\': None}, {\'credit_id\': \'55eda200c3a3682c5d016a8f\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1375920, \'job\': \'Additional Camera\', \'name\': \'J. Christopher Campbell\', \'profile_path\': None}, {\'credit_id\': \'55eda228c3a3682c64013295\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1403412, \'job\': \'Gaffer\', \'name\': \'Dan Cornwall\', \'profile_path\': None}, {\'credit_id\': \'55eda25f92514106d600da4b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1442137, \'job\': \'Animation Supervisor\', \'name\': \'Catherine Mullan\', \'profile_path\': None}, {\'credit_id\': \'55eda292c3a3682c5d016ab2\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1393405, \'job\': \'Music Editor\', \'name\': \'Robb Boyd\', \'profile_path\': None}, {\'credit_id\': \'55eda2a9c3a3682c6b014075\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1328758, \'job\': \'Music Editor\', \'name\': \'Matthew Llewellyn\', \'profile_path\': None}, {\'credit_id\': \'55eda2c89251413e45014a6d\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1389138, \'job\': \'Script Supervisor\', \'name\': \'Jody Blose\', \'profile_path\': None}, {\'credit_id\': \'55eda305c3a3682c700149c1\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1408365, \'job\': \'Script Supervisor\', \'name\': \'Brenda K. Wachel\', \'profile_path\': None}, {\'credit_id\': \'55eda32dc3a3686f17003ddd\', \'department\': \'Crew\', \'gender\': 2, \'id\': 8167, \'job\': \'Thanks\', \'name\': \'Paul Walker\', \'profile_path\': \'/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg\'}, {\'credit_id\': \'55eda3b592514106d600da94\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1400354, \'job\': \'Digital Intermediate\', \'name\': \'Amy Pawlowski\', \'profile_path\': None}, {\'credit_id\': \'55eda3d792514106d600da9b\', \'department\': \'Editing\', \'gender\': 0, \'id\': 110262, \'job\': \'First Assistant Editor\', \'name\': \'Richard Conkling\', \'profile_path\': None}, {\'credit_id\': \'55eda3edc3a3686f17003e0c\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1194885, \'job\': \'First Assistant Editor\', \'name\': \'Dave  Cory\', \'profile_path\': None}, {\'credit_id\': \'55eda4169251413e410148ec\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1439749, \'job\': \'First Assistant Editor\', \'name\': \'Laura Steiger\', \'profile_path\': None}, {\'credit_id\': \'55eda48092514106d600daba\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1506377, \'job\': \'Animation Supervisor\', \'name\': \'Daniel Barrett\', \'profile_path\': \'/pplTJP3gCWmP3SMDrXjOt1579MV.jpg\'}, {\'credit_id\': \'55eda5109251413e32014cf0\', \'department\': \'Sound\', \'gender\': 0, \'id\': 12562, \'job\': \'ADR & Dubbing\', \'name\': \'Anna MacKenzie\', \'profile_path\': None}, {\'credit_id\': \'55eda51ac3a3686f17003e52\', \'department\': \'Editing\', \'gender\': 0, \'id\': 12562, \'job\': \'Dialogue Editor\', \'name\': \'Anna MacKenzie\', \'profile_path\': None}, {\'credit_id\': \'55eda539c3a368090c0051c2\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1342658, \'job\': \'Dialogue Editor\', \'name\': \'Frederick H. Stahly\', \'profile_path\': None}, {\'credit_id\': \'55eda56a9251413e45014adf\', \'department\': \'Sound\', \'gender\': 2, \'id\': 1077782, \'job\': \'Foley\', \'name\': \'Gary A. Hecker\', \'profile_path\': \'/qyBUauN3XIS2Mlus3OdGCmrUo0S.jpg\'}, {\'credit_id\': \'55eda58292514106d600daf4\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1367362, \'job\': \'Foley\', \'name\': \'Rick Owens\', \'profile_path\': None}, {\'credit_id\': \'55eda59ac3a3682c5d016b50\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1236340, \'job\': \'Foley\', \'name\': \'Dylan Tuomy-Wilhoit\', \'profile_path\': None}, {\'credit_id\': \'55eda5b09251413e45014af1\', \'department\': \'Sound\', \'gender\': 0, \'id\': 548445, \'job\': \'Foley\', \'name\': \'Jeffrey Wilhoit\', \'profile_path\': None}, {\'credit_id\': \'55eda7169251413e45014b3b\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7239, \'job\': \'Sound Designer\', \'name\': \'Peter Brown\', \'profile_path\': None}, {\'credit_id\': \'55eda73d9251413e4101498c\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1392083, \'job\': \'Sound Designer\', \'name\': \'Ann Scibelli\', \'profile_path\': None}, {\'credit_id\': \'55eda779c3a3682c70014abc\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1413453, \'job\': \'Sound Effects Editor\', \'name\': \'Stephen P. Robinson\', \'profile_path\': None}, {\'credit_id\': \'55eda7989251413e3e015838\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1394131, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Jon Taylor\', \'profile_path\': None}, {\'credit_id\': \'55eda7afc3a3686f17003ebf\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1394130, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Frank A. Monta√±o\', \'profile_path\': None}, {\'credit_id\': \'55eda7d79251413e32014e11\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1309884, \'job\': \'Supervising Sound Editor\', \'name\': \'Joe Dzuban\', \'profile_path\': None}, {\'credit_id\': \'570bd40dc3a36802a30002d9\', \'department\': \'Art\', \'gender\': 0, \'id\': 1424153, \'job\': \'Supervising Art Director\', \'name\': \'Desma Murphy\', \'profile_path\': None}, {\'credit_id\': \'5668cc7a92514174040040f2\', \'department\': \'Sound\', \'gender\': 2, \'id\': 6041, \'job\': \'Original Music Composer\', \'name\': \'Brian Tyler\', \'profile_path\': \'/22QWiNJj03amY6GT1QPUs7dbdcB.jpg\'}, {\'credit_id\': \'58ebe1fa925141281008e943\', \'department\': \'Production\', \'gender\': 2, \'id\': 58191, \'job\': \'Executive Producer\', \'name\': \'Chris Morgan\', \'profile_path\': \'/dUGxIwFBLrSFLImxjeda1krndMO.jpg\'}]'

In [ ]:
Producer_list = []
Director_list = []
for i in eval(max_profit_movie['crew']):
  if i['job'] == 'Producer':
    Producer_list.append(i['name'])

print(Producer_list)

for i in eval(max_profit_movie['crew']):
  if i['job'] == 'Director':
    Director_list.append(i['name'])

print(Director_list)

['Vin Diesel', 'Neal H. Moritz', 'Michael Fottrell', 'Brandon Birtell']
['James Wan']

In [ ]:
print(f'Most profitable Movie Name: {max_profit_movie_name}')
print(f'Most profitable Producer: {Producer_list}')
print(f'Most profitable Director: {Director_list}')
print(f'Most profitable Actors: {actor_name}')

Most profitable Movie Name: Furious 7
Most profitable Producer: ['Vin Diesel', 'Neal H. Moritz', 'Michael Fottrell', 'Brandon Birtell']
Most profitable Director: ['James Wan']
Most profitable Actors: ['Vin Diesel', 'Paul Walker', 'Dwayne Johnson', 'Michelle Rodriguez', 'Tyrese Gibson', 'Ludacris', 'Jordana Brewster', 'Djimon Hounsou', 'Tony Jaa', 'Ronda Rousey', 'Nathalie Emmanuel', 'Kurt Russell', 'Jason Statham', 'Sung Kang', 'Gal Gadot', 'Lucas Black', 'Elsa Pataky', 'Noel Gugliemi', 'John Brotherton', 'Luke Evans', 'Ali Fazal', 'Miller Kimsey', 'Charlie Kimsey', 'Eden Estrella', 'Gentry White', 'Iggy Azalea', 'Jon Lee Brody', 'Levy Tran', 'Anna Colwell', 'Viktor Hernandez', 'Steve Coulter', 'Robert Pralgo', 'Antwan Mills', 'J.J. Phillips', 'Jorge Ferragut', 'Sara Sohn', 'Benjamin Blankenship', 'D.J. Hapa', 'T-Pain', 'Brian Mahoney', 'Brittney Alger', 'Romeo Santos', 'Jocelin Donahue', 'Stephanie Langston', 'Jorge-Luis Pallo', 'Tego Calder√≥n', 'Nathalie Kelley', 'Shad Moss', 'Don Omar', 'Klement Tinaj', 'Caleb Walker', 'Cody Walker']

In [ ]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970

#Q2.This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)?

In [ ]:
df['ROI'] = 100*df['profit']/df['budget']
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit,ROI
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,-12.038207
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,137.873588
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,296.727273
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,1233.333333
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,inf

In [ ]:
df['original_language'].value_counts()

original_language
en    2575
fr      78
ru      47
es      43
hi      42
ja      37
it      24
cn      20
ko      20
zh      19
de      18
ta      16
sv       8
nl       6
pt       6
fa       5
da       5
ro       4
hu       3
tr       3
no       2
ml       2
pl       2
te       2
fi       2
ur       1
he       1
el       1
ar       1
nb       1
vi       1
mr       1
cs       1
sr       1
bn       1
id       1
Name: count, dtype: int64

In [ ]:
df.describe()

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:4655: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,id,budget,popularity,runtime,revenue,profit,ROI
count,3000.000000,3.000000e+03,3000.000000,2998.000000,3.000000e+03,3.000000e+03,3000.000000
mean,1500.500000,2.253133e+07,8.463274,107.856571,6.672585e+07,4.419452e+07,inf
std,866.169729,3.702609e+07,12.104000,22.086434,1.375323e+08,1.123274e+08,NaN
min,1.000000,0.000000e+00,0.000001,0.000000,1.000000e+00,-1.074474e+08,-99.999948
25%,750.750000,0.000000e+00,4.018053,94.000000,2.379808e+06,1.795200e+04,17.176318
50%,1500.500000,8.000000e+06,7.374861,104.000000,1.680707e+07,6.121122e+06,239.984076
75%,2250.250000,2.900000e+07,10.890983,118.000000,6.891920e+07,4.143293e+07,NaN
max,3000.000000,3.800000e+08,294.337037,338.000000,1.519558e+09,1.316249e+09,inf

In [ ]:
print(df['budget'].mean())
print(df['budget'].median())

22531334.11
8000000.0

In [ ]:
print(df['revenue'].mean())
print(df['revenue'].median())

66725851.88866667
16807068.0

In [ ]:
df.loc[df['revenue']<1000,'revenue'] = df['revenue'].median()
df.loc[df['budget']<1000,'budget'] = df['budget'].median()

In [ ]:
df.describe()

/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:4655: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,id,budget,popularity,runtime,revenue,profit,ROI
count,3000.000000,3.000000e+03,3000.000000,2998.000000,3.000000e+03,3.000000e+03,3000.000000
mean,1500.500000,2.474467e+07,8.463274,107.856571,6.704518e+07,4.419452e+07,inf
std,866.169729,3.583254e+07,12.104000,22.086434,1.373964e+08,1.123274e+08,NaN
min,1.000000,2.500000e+03,0.000001,0.000000,1.404000e+03,-1.074474e+08,-99.999948
25%,750.750000,8.000000e+06,4.018053,94.000000,2.947600e+06,1.795200e+04,17.176318
50%,1500.500000,8.000000e+06,7.374861,104.000000,1.680873e+07,6.121122e+06,239.984076
75%,2250.250000,2.900000e+07,10.890983,118.000000,6.891920e+07,4.143293e+07,NaN
max,3000.000000,3.800000e+08,294.337037,338.000000,1.519558e+09,1.316249e+09,inf

In [ ]:
df['profit'] = df['revenue'] - df['budget']

In [ ]:
df['ROI'] = 100*df['profit']/df['budget']

In [ ]:
df.groupby('original_language')['ROI'].mean().sort_values(ascending=False).head()

original_language
ko    11309.685605
el     5198.013245
sr     3261.413600
en      952.119148
tr      878.917604
Name: ROI, dtype: float64

In [ ]:
df.groupby('original_language')['profit'].mean().sort_values(ascending=False)

original_language
zh    5.063183e+07
en    4.758996e+07
tr    4.616341e+07
ja    1.978658e+07
hi    1.887854e+07
cn    1.809881e+07
sr    1.630707e+07
de    1.423675e+07
pl    1.133119e+07
it    9.201048e+06
he    9.125849e+06
ta    9.038196e+06
el    7.849000e+06
sv    6.856393e+06
te    6.642485e+06
ko    6.187907e+06
fr    6.074406e+06
da    3.757093e+06
mr    2.900000e+06
es    2.037021e+06
ml    1.105000e+06
ru    9.933813e+05
nb    6.596780e+05
ur    5.019860e+05
fi   -5.263340e+05
vi   -6.610000e+05
id   -1.872791e+06
ro   -2.490350e+06
nl   -2.933666e+06
no   -3.388932e+06
pt   -4.381349e+06
fa   -5.723815e+06
hu   -5.941874e+06
ar   -6.652253e+06
bn   -7.463636e+06
cs   -7.982607e+06
Name: profit, dtype: float64

In [ ]:
df.groupby('original_language')['profit'].median().sort_values(ascending=False)

original_language
sr    16307068.0
pl    11331194.0
ja    11204593.0
he     9125849.0
zh     8807068.0
hi     8453534.0
el     7849000.0
en     6744356.0
te     6642485.0
ta     6500000.0
cn     5822383.5
tr     4830000.0
mr     2900000.0
ml     1105000.0
ko     1070165.0
nb      659678.0
ur      501986.0
it      257354.0
de      -17890.5
fi     -526334.0
sv     -594779.0
vi     -661000.0
ro    -1157670.0
ru    -1606184.0
id    -1872791.0
da    -2594687.0
nl    -2997447.0
no    -3388932.5
es    -3632503.0
pt    -4082793.5
fr    -5340029.0
ar    -6652253.0
bn    -7463636.0
fa    -7884395.0
hu    -7933441.0
cs    -7982607.0
Name: profit, dtype: float64

In [ ]:
df.groupby('original_language')['profit'].max().sort_values(ascending=False)

original_language
en    1316249360
fr     413480871
zh     345284817
hi     299600000
it     209400000
tr     141521495
cn     120844753
ja     103949270
de      75027924
es      59600000
sv      58995253
ru      50635037
ko      47558912
ta      35600000
da      31570000
sr      16307068
pl      13139075
te      11084261
he       9125849
el       7849000
mr       2900000
pt       2696708
ml       2200000
no       1184662
nl        940000
fa        720000
nb        659678
ur        501986
ro        333273
fi        215063
vi       -661000
id      -1872791
hu      -1917642
ar      -6652253
bn      -7463636
cs      -7982607
Name: profit, dtype: int64

In [ ]:
df.groupby('original_language')['profit'].min().sort_values(ascending=False)

original_language
sr     16307068
pl      9523313
he      9125849
el      7849000
mr      2900000
te      2200709
nb       659678
ur       501986
ml        10000
ta            0
vi      -661000
fi     -1267731
id     -1872791
ar     -6652253
bn     -7463636
nl     -7796219
sv     -7819410
da     -7820057
tr     -7861270
es     -7947239
fa     -7962402
no     -7962527
hu     -7974539
ro     -7979334
cs     -7982607
ko     -7997660
it    -11360000
pt    -13297099
hi    -16500000
de    -17959761
ru    -18500000
cn    -24870885
ja    -25113768
fr    -31748929
zh    -32600000
en   -107447384
Name: profit, dtype: int64

In [ ]:
df.groupby('original_language')['profit'].sum().sort_values(ascending=False)

original_language
en    122544158200
zh       962004760
hi       792898728
ja       732103609
fr       473803648
cn       361976174
de       256261447
it       220825157
ta       144611129
tr       138490225
ko       123758143
es        87591890
sv        54851147
ru        46688921
pl        22662388
da        18785467
sr        16307068
te        13284970
he         9125849
el         7849000
mr         2900000
ml         2210000
nb          659678
ur          501986
vi         -661000
fi        -1052668
id        -1872791
ar        -6652253
no        -6777865
bn        -7463636
cs        -7982607
ro        -9961401
nl       -17601998
hu       -17825622
pt       -26288096
fa       -28619074
Name: profit, dtype: int64

#Q3.Find out the unique genres of movies in this dataset.

In [ ]:
df['genres'].isnull().sum()

7

In [ ]:
not_null_genere = df[df['genres'].notnull()]
not_null_genere.isnull().sum()

id                          0
belongs_to_collection    2389
budget                      0
genres                      0
homepage                 2048
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      149
production_countries       52
release_date                0
runtime                     2
spoken_languages           17
status                      0
tagline                   591
title                       0
Keywords                  271
cast                       13
crew                       15
revenue                     0
profit                      0
ROI                         0
dtype: int64

In [ ]:
not_null_genere.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit,ROI
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,-12.038207
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,137.873588
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,296.727273
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,1233.333333
4,5,NaN,8000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,-4076030,-50.950375

In [ ]:
genere = []
for i in not_null_genere['genres']:
  for j in eval(i):
    genere.append(j['name'])

print(genere)

['Comedy', 'Comedy', 'Drama', 'Family', 'Romance', 'Drama', 'Thriller', 'Drama', 'Action', 'Thriller', 'Animation', 'Adventure', 'Family', 'Horror', 'Thriller', 'Documentary', 'Action', 'Comedy', 'Music', 'Family', 'Adventure', 'Comedy', 'Music', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Crime', 'Action', 'Thriller', 'Science Fiction', 'Mystery', 'Action', 'Crime', 'Drama', 'Horror', 'Thriller', 'Drama', 'Romance', 'Comedy', 'Romance', 'Action', 'Thriller', 'Crime', 'Adventure', 'Family', 'Science Fiction', 'Horror', 'Thriller', 'Thriller', 'Horror', 'Thriller', 'Mystery', 'Foreign', 'Horror', 'Comedy', 'Comedy', 'Horror', 'Mystery', 'Thriller', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Animation', 'Action', 'Adventure', 'Crime', 'Thriller', 'Drama', 'Comedy', 'Mystery', 'Drama', 'Thriller', 'Fantasy', 'Action', 'Adventure', 'Horror', 'Action', 'Comedy', 'Crime', 'Thriller', 'Action', 'Crime', 'Thriller', 'Comedy', 'Romance', 'Action', 'Drama', 'Science Fiction', 'Thriller', 'Thriller', 'War', 'Western', 'Action', 'Documentary', 'Crime', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Romance', 'Crime', 'Drama', 'Mystery', 'Romance', 'Thriller', 'Animation', 'Family', 'Comedy', 'Adventure', 'Crime', 'Drama', 'Mystery', 'Western', 'Drama', 'Comedy', 'Science Fiction', 'Action', 'Adventure', 'Thriller', 'Romance', 'Drama', 'Comedy', 'Adventure', 'Comedy', 'Adventure', 'Family', 'Drama', 'Family', 'Romance', 'Action', 'Comedy', 'Drama', 'Romance', 'Comedy', 'Drama', 'Action', 'Crime', 'Fantasy', 'Music', 'Romance', 'Action', 'Adventure', 'Comedy', 'Adventure', 'Action', 'Thriller', 'Drama', 'Thriller', 'Fantasy', 'Crime', 'Drama', 'Horror', 'Thriller', 'Drama', 'Adventure', 'Action', 'Crime', 'Comedy', 'Drama', 'Crime', 'Drama', 'Action', 'Crime', 'Drama', 'Thriller', 'Drama', 'Mystery', 'Thriller', 'Fantasy', 'Drama', 'Comedy', 'Music', 'Crime', 'Documentary', 'Crime', 'Drama', 'Horror', 'Comedy', 'Drama', 'Romance', 'Foreign', 'Comedy', 'Crime', 'Drama', 'Action', 'Thriller', 'Horror', 'Thriller', 'Action', 'Crime', 'Drama', 'Thriller', 'Comedy', 'Drama', 'Romance', 'Drama', 'Horror', 'Mystery', 'Thriller', 'Thriller', 'Science Fiction', 'Horror', 'Mystery', 'Action', 'Adventure', 'Drama', 'Mystery', 'Science Fiction', 'Thriller', 'Drama', 'Crime', 'Action', 'Comedy', 'Thriller', 'Drama', 'History', 'Drama', 'Thriller', 'Mystery', 'Romance', 'Action', 'Crime', 'Drama', 'War', 'Adventure', 'Drama', 'Romance', 'Drama', 'History', 'Thriller', 'Drama', 'Mystery', 'Drama', 'Action', 'Comedy', 'Thriller', 'Romance', 'Fantasy', 'Drama', 'Animation', 'Comedy', 'Adventure', 'Family', 'Action', 'Crime', 'Drama', 'Action', 'Thriller', 'Science Fiction', 'Crime', 'Horror', 'Drama', 'Romance', 'Action', 'Comedy', 'Crime', 'Foreign', 'Drama', 'Comedy', 'Drama', 'Drama', 'Action', 'Drama', 'History', 'War', 'Drama', 'Comedy', 'Romance', 'Drama', 'Adventure', 'Romance', 'Action', 'Comedy', 'Crime', 'Romance', 'Comedy', 'Romance', 'Drama', 'Thriller', 'Drama', 'Adventure', 'Action', 'History', 'Comedy', 'Drama', 'Romance', 'Adventure', 'Fantasy', 'Action', 'Action', 'Comedy', 'Drama', 'Action', 'Adventure', 'Comedy', 'Drama', 'Romance', 'Crime', 'Action', 'Comedy', 'Action', 'Comedy', 'Crime', 'Thriller', 'Adventure', 'Animation', 'Drama', 'Family', 'Action', 'Comedy', 'Crime', 'Mystery', 'Thriller', 'Action', 'Crime', 'Thriller', 'Comedy', 'Drama', 'Romance', 'Drama', 'War', 'Action', 'Adventure', 'Comedy', 'Horror', 'Drama', 'Thriller', 'Mystery', 'Horror', 'Thriller', 'Drama', 'Comedy', 'Drama', 'Thriller', 'Documentary', 'History', 'Comedy', 'Drama', 'Comedy', 'Romance', 'Adventure', 'Comedy', 'Drama', 'Drama', 'Family', 'Comedy', 'Thriller', 'Adventure', 'Action', 'Science Fiction', 'Thriller', 'Drama', 'Music', 'Romance', 'Drama', 'Romance', 'Drama', 'Comedy', 'Drama', 'Horror', 'Crime', 'Thriller', 'Drama', 'Mystery', 'Romance', 'Comedy', 'Crime', 'Action', 'Science Fiction', 'Drama', 'Comedy', 'Family', 'Thriller', 'Adventure', 'Drama', 'Adventure', 'Drama', 'Western', 'Documentary', 'Drama', 'Fantasy', 'Horror', 'Thriller', 'Action', 'Crime', 'Thriller', 'Adventure', 'Fantasy', 'Animation', 'Family', 'Action', 'Action', 'Adventure', 'Science Fiction', 'Action', 'Drama', 'Thriller', 'Crime', 'Action', 'Western', 'Comedy', 'Drama', 'Comedy', 'Romance', 'Drama', 'Comedy', 'Comedy', 'Drama', 'Thriller', 'Horror', 'Fantasy', 'Action', 'Comedy', 'Science Fiction', 'Romance', 'Documentary', 'Music', 'Crime', 'Drama', 'Horror', 'Thriller', 'Mystery', 'Comedy', 'Crime', 'Adventure', 'Action', 'Thriller', 'Science Fiction', 'Comedy', 'Crime', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Action', 'Drama', 'Thriller', 'Crime', 'Mystery', 'Adventure', 'Comedy', 'Action', 'Crime', 'Thriller', 'Horror', 'Science Fiction', 'Thriller', 'Drama', 'Romance', 'Action', 'Adventure', 'Thriller', 'War', 'Adventure', 'Action', 'Thriller', 'Thriller', 'Crime', 'Drama', 'Drama', 'Comedy', 'Romance', 'Adventure', 'Drama', 'Action', 'Comedy', 'Drama', 'Fantasy', 'Romance', 'Drama', 'Crime', 'Comedy', 'Drama', 'Mystery', 'Animation', 'Family', 'Drama', 'Comedy', 'Horror', 'Thriller', 'Science Fiction', 'Romance', 'Comedy', 'Drama', 'Comedy', 'Action', 'Crime', 'Drama', 'Thriller', 'Comedy', 'Drama', 'Drama', 'Horror', 'Action', 'Thriller', 'Crime', 'Action', 'Comedy', 'Drama', 'Drama', 'Crime', 'Comedy', 'Family', 'Fantasy', 'Music', 'Comedy', 'Drama', 'Romance', 'Science Fiction', 'Animation', 'Comedy', 'Family', 'Animation', 'Comedy', 'Family', 'Horror', 'Comedy', 'Romance', 'Crime', 'Drama', 'Thriller', 'Crime', 'Drama', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Family', 'Fantasy', 'Fantasy', 'Horror', 'Science Fiction', 'Western', 'Adventure', 'Horror', 'Comedy', 'Horror', 'Thriller', 'Adventure', 'Action', 'Comedy', 'Family', 'Action', 'Thriller', 'Crime', 'Drama', 'Comedy', 'Crime', 'Fantasy', 'Animation', 'Family', 'Action', 'Comedy', 'Comedy', 'Documentary', 'Drama', 'History', 'War', 'Comedy', 'Romance', 'Comedy', 'Drama', 'Romance', 'Thriller', 'Mystery', 'Comedy', 'Action', 'Adventure', 'Drama', 'History', 'Fantasy', 'Thriller', 'Action', 'Crime', 'Drama', 'Romance', 'Adventure', 'Western', 'Drama', 'Romance', 'Action', 'Adventure', 'Comedy', 'Drama', 'Romance', 'Comedy', 'Drama', 'Western', 'Documentary', 'Action', 'Adventure', 'Drama', 'History', 'Adventure', 'Family', 'Horror', 'Comedy', 'Comedy', 'Fantasy', 'Drama', 'Thriller', 'Mystery', 'Romance', 'Drama', 'Romance', 'Comedy', 'Music', 'Action', 'Drama', 'Animation', 'Music', 'Family', 'Animation', 'Comedy', 'Drama', 'Romance', 'Romance', 'Comedy', 'Horror', 'Comedy', 'Adventure', 'Romance', 'Romance', 'Comedy', 'Crime', 'Fantasy', 'Drama', 'History', 'War', 'Action', 'Crime', 'Thriller', 'Mystery', 'Comedy', 'Action', 'Adventure', 'Comedy', 'Horror', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Adventure', 'Drama', 'Drama', 'Action', 'Western', 'Music', 'Romance', 'Action', 'Animation', 'Science Fiction', 'Drama', 'Drama', 'Family', 'Comedy', 'Drama', 'Romance', 'Science Fiction', 'Drama', 'Thriller', 'Crime', 'Drama', 'Adventure', 'Drama', 'Comedy', 'Adventure', 'Action', 'Family', 'Documentary', 'Foreign', 'Music', 'Family', 'Comedy', 'Comedy', 'Action', 'Thriller', 'Family', 'Comedy', 'Comedy', 'Romance', 'Documentary', 'Horror', 'Fantasy', 'Thriller', 'Action', 'Adventure', 'Comedy', 'Romance', 'Drama', 'Drama', 'Crime', 'Thriller', 'Horror', 'Thriller', 'Horror', 'Thriller', 'Comedy', 'Drama', 'Romance', 'Drama', 'Crime', 'Drama', 'Thriller', 'Comedy', 'Science Fiction', 'Thriller', 'Adventure', 'Horror', 'Thriller', 'Thriller', 'Comedy', 'Crime', 'Romance', 'Action', 'Drama', 'Animation', 'Drama', 'Family', 'Fantasy', 'Comedy', 'Drama', 'Romance', 'Crime', 'Drama', 'Thriller', 'Drama', 'War', 'Action', 'Drama', 'Foreign', 'History', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Action', 'Fantasy', 'Science Fiction', 'Drama', 'Action', 'Crime', 'Drama', 'Comedy', 'Fantasy', 'Action', 'Comedy', 'Science Fiction', 'Action', 'Horror', 'Comedy', 'Romance', 'Comedy', 'Music', 'Romance', 'Drama', 'Thriller', 'Action', 'War', 'Drama', 'History', 'Crime', 'Family', 'Fantasy', 'Crime', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Drama', 'Thriller', 'Mystery', 'Drama', 'Romance', 'Comedy', 'Drama', 'Drama', 'Comedy', 'Family', 'Comedy', 'Animation', 'Adventure', 'Crime', 'Drama', 'Mystery', 'Animation', 'Adventure', 'Family', 'Comedy', 'Science Fiction', 'Action', 'Drama', 'Thriller', 'Fantasy', 'Mystery', 'Thriller', 'Crime', 'Drama', 'Romance', 'Thriller', 'Action', 'Thriller', 'Adventure', 'Fantasy', 'Drama', 'Comedy', 'Science Fiction', 'Family', 'Western', 'Drama', 'Adventure', 'Thriller', 'Drama', 'Action', 'Thriller', 'Crime', 'Action', 'Comedy', 'Romance', 'Comedy', 'Family', 'Fantasy', 'Comedy', 'Action', 'Thriller', 'Crime', 'Drama', 'Drama', 'Romance', 'Animation', 'Comedy', 'Romance', 'Adventure', 'Drama', 'Action', 'History', 'Comedy', 'Drama', 'Romance', 'War', 'Action', 'Drama', 'Action', 'Drama', 'Drama', 'Thriller', 'Crime', 'Mystery', 'Drama', 'Fantasy', 'Drama', 'Drama', 'History', 'Comedy', 'Drama', 'Mystery', 'Thriller', 'Crime', 'Comedy', 'Romance', 'War', 'Drama', 'Action', 'Action', 'Drama', 'Thriller', 'Comedy', 'Romance', 'Drama', 'Romance', 'Fantasy', 'Drama', 'Comedy', 'Family', 'Adventure', 'Adventure', 'Animation', 'Fantasy', 'Documentary', 'Drama', 'Action', 'Adventure', 'Action', 'Thriller', 'Comedy', 'Action', 'Comedy', 'Action', 'Crime', 'Documentary', 'Action', 'Adventure', 'Comedy', 'Drama', 'Mystery', 'Family', 'Animation', 'Drama', 'Action', 'War', 'Science Fiction', 'Fantasy', 'Drama', 'Family', 'Documentary', 'Adventure', 'Action', 'Comedy', 'Crime', 'Drama', 'War', 'Drama', 'Romance', 'Drama', 'Thriller', 'Science Fiction', 'Drama', 'Thriller', 'Drama', 'Family', 'Adventure', 'Comedy', 'Fantasy', 'Drama', 'Comedy', 'Romance', 'Thriller', 'Horror', 'Comedy', 'Drama', 'Drama', 'Comedy', 'Romance', 'Foreign', 'Action', 'Drama', 'Thriller', 'War', 'Comedy', 'Thriller', 'Drama', 'Horror', 'Science Fiction', 'Science Fiction', 'Animation', 'Family', 'Drama', 'Thriller', 'Crime', 'Animation', 'Family', 'Adventure', 'Drama', 'Music', 'Drama', 'Thriller', 'Action', 'Adventure', 'Drama', 'Family', 'Crime', 'Drama', 'Thriller', 'Drama', 'Romance', 'Drama', 'Family', 'Comedy', 'Drama', 'Drama', 'Romance', 'Action', 'Crime', 'Drama', 'Thriller', 'Comedy', 'Comedy', 'Adventure', 'Drama', 'History', 'Drama', 'Family', 'Comedy', 'Comedy', 'Comedy', 'Drama', 'Comedy', 'Documentary', 'Drama', 'Horror', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Drama', 'History', 'Romance', 'War', 'Comedy', 'Crime', 'Horror', 'Thriller', 'Romance', 'Comedy', 'Drama', 'History', 'Drama', 'Action', 'Action', 'Horror', 'Thriller', 'Science Fiction', 'Horror', 'Thriller', 'Mystery', 'Animation', 'Comedy', 'Fantasy', 'Thriller', 'Adventure', 'Comedy', 'Science Fiction', 'Drama', 'Horror', 'Action', 'Thriller', 'Science Fiction', 'Drama', 'History', 'Romance', 'Comedy', 'Romance', 'Comedy', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Adventure', 'Horror', 'Thriller', 'Crime', 'Drama', 'Comedy', 'Foreign', 'Fantasy', 'Comedy', 'Romance', 'Horror', 'Thriller', 'Action', 'Comedy', 'Crime', 'Thriller', 'Mystery', 'Comedy', 'Drama', 'Drama', 'Fantasy', 'Comedy', 'Family', 'Comedy', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Mystery', 'Thriller', 'Comedy', 'Science Fiction', 'Thriller', 'Crime', 'Drama', 'Mystery', 'Action', 'Comedy', 'Crime', 'Romance', 'Adventure', 'Comedy', 'Drama', 'Science Fiction', 'Family', 'Adventure', 'Drama', 'Drama', 'History', 'Adventure', 'Action', 'Comedy', 'Comedy', 'Romance', 'Drama', 'Action', 'War', 'Drama', 'Thriller', 'Documentary', 'Mystery', 'Thriller', 'Drama', 'Romance', 'Comedy', 'Drama', 'Adventure', 'Action', 'Science Fiction', 'Thriller', 'Fantasy', 'Drama', 'Comedy', 'Family', 'Action', 'Thriller', 'Thriller', 'Science Fiction', 'Adventure', 'Action', 'Comedy', 'Romance', 'Drama', 'Crime', 'Thriller', 'Music', 'Romance', 'Drama', 'Horror', 'Thriller', 'War', 'Comedy', 'Drama', 'Romance', 'Horror', 'Drama', 'Mystery', 'Drama', 'Romance', 'Comedy', 'Family', 'Thriller', 'Action', 'Crime', 'History', 'Drama', 'Comedy', 'Family', 'Drama', 'Science Fiction', 'Mystery', 'Comedy', 'Drama', 'Family', 'Comedy', 'Family', 'Science Fiction', 'Crime', 'Drama', 'Thriller', 'Drama', 'Comedy', 'Drama', 'Adventure', 'Drama', 'Action', 'Romance', 'Family', 'Comedy', 'Drama', 'Crime', 'Thriller', 'Action', 'Comedy', 'Drama', 'History', 'Family', 'Animation', 'Horror', 'Comedy', 'Drama', 'Comedy', 'Drama', 'Action', 'Adventure', 'Drama', 'Thriller', 'Fantasy', 'Drama', 'Comedy', 'Science Fiction', 'Romance', 'Western', 'Action', 'Adventure', 'Comedy', 'Drama', 'Comedy', 'Drama', 'Romance', 'Drama', 'Comedy', 'Romance', 'Crime', 'Drama', 'History', 'Drama', 'Romance', 'Adventure', 'Animation', 'Comedy', 'Drama', 'Fantasy', 'Horror', 'Thriller', 'Drama', 'Horror', 'Science Fiction', 'Animation', 'Comedy', 'Drama', 'Action', 'Adventure', 'Drama', 'History', 'Crime', 'Drama', 'Thriller', 'Drama', 'Romance', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Action', 'Thriller', 'Horror', 'Mystery', 'Science Fiction', 'Action', 'Adventure', 'Thriller', 'Documentary', 'Animation', 'Comedy', 'Family', 'War', 'Drama', 'Comedy', 'Drama', 'Romance', 'Action', 'Drama', 'Thriller', 'Mystery', 'Crime', 'Drama', 'Western', 'Action', 'Drama', 'War', 'Comedy', 'Drama', 'Thriller', 'Crime', 'Action', 'Mystery', 'Drama', 'Thriller', 'Horror', 'Crime', 'Drama', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Comedy', 'Drama', 'Romance', 'Thriller', 'Science Fiction', 'Action', 'Crime', 'Drama', 'Music', 'Romance', 'Horror', 'Mystery', 'Thriller', 'Romance', 'Drama', 'Drama', 'Romance', 'Action', 'Adventure', 'Fantasy', 'Drama', 'Action', 'Crime', 'Drama', 'Documentary', 'Music', 'Drama', 'Drama', 'History', 'Action', 'Drama', 'Thriller', 'Adventure', 'Action', 'Thriller', 'Crime', 'Adventure', 'Comedy', 'Romance', 'Comedy', 'Romance', 'Romance', 'Comedy', 'Crime', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Romance', 'Drama', 'Documentary', 'Music', 'Family', 'Adventure', 'Action', 'Science Fiction', 'Adventure', 'Thriller', 'Drama', 'Romance', 'Drama', 'War', 'Comedy', 'Action', 'Adventure', 'Thriller', 'Adventure', 'Action', 'Comedy', 'Documentary', 'Adventure', 'Family', 'Fantasy', 'Comedy', 'Drama', 'Horror', 'Mystery', 'Thriller', 'Adventure', 'Fantasy', 'Action', 'Comedy', 'Drama', 'Music', 'Romance', 'Action', 'Adventure', 'Drama', 'Drama', 'Comedy', 'Thriller', 'Comedy', 'Fantasy', 'Horror', 'Horror', 'Thriller', 'Documentary', 'Thriller', 'Drama', 'Crime', 'Action', 'Science Fiction', 'Horror', 'Thriller', 'Comedy', 'Crime', 'Romance', 'Drama', 'Animation', 'Science Fiction', 'Action', 'Adventure', 'Crime', 'Drama', 'Thriller', 'Adventure', 'Drama', 'Comedy', 'Comedy', 'Drama', 'History', 'Adventure', 'Family', 'Drama', 'Drama', 'Comedy', 'Romance', 'Drama', 'Drama', 'Comedy', 'Romance', 'Action', 'Adventure', 'Drama', 'History', 'Western', 'Action', 'Comedy', 'Crime', 'Drama', 'Thriller', 'Science Fiction', 'Thriller', 'Horror', 'Thriller', 'Science Fiction', 'Horror', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Comedy', 'Comedy', 'Drama', 'History', 'Action', 'Science Fiction', 'Crime', 'Adventure', 'Animation', 'Comedy', 'Family', 'Drama', 'Action', 'Western', 'Drama', 'Comedy', 'Horror', 'Music', 'Drama', 'Comedy', 'Drama', 'Music', 'Horror', 'Action', 'Thriller', 'Crime', 'Comedy', 'Drama', 'Drama', 'Music', 'Action', 'Horror', 'Science Fiction', 'Horror', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Drama', 'Comedy', 'Drama', 'Romance', 'Romance', 'Drama', 'Comedy', 'Romance', 'Comedy', 'Horror', 'Comedy', 'Fantasy', 'Comedy', 'Drama', 'Drama', 'Thriller', 'Drama', 'Action', 'Romance', 'War', 'Drama', 'Thriller', 'Adventure', 'Drama', 'Romance', 'Action', 'Comedy', 'Romance', 'Drama', 'Drama', 'Action', 'Crime', 'Thriller', 'Drama', 'History', 'War', 'Thriller', 'War', 'Adventure', 'Documentary', 'Drama', 'Fantasy', 'Animation', 'Romance', 'Family', 'Horror', 'Comedy', 'Action', 'Fantasy', 'Science Fiction', 'Thriller', 'Drama', 'Romance', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Action', 'Adventure', 'Drama', 'War', 'Drama', 'Foreign', 'Drama', 'Family', 'Comedy', 'Comedy', 'Fantasy', 'Drama', 'Mystery', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Drama', 'War', 'Drama', 'History', 'Adventure', 'Fantasy', 'Action', 'Comedy', 'Family', 'Action', 'Comedy', 'Action', 'Adventure', 'Drama', 'History', 'Music', 'Drama', 'Action', 'Drama', 'Thriller', 'Drama', 'Drama', 'Romance', 'Comedy', 'Drama', 'Romance', 'Adventure', 'Comedy', 'Crime', 'Mystery', 'Romance', 'Thriller', 'Thriller', 'Action', 'Crime', 'Drama', 'Action', 'Adventure', 'Fantasy', 'Science Fiction', 'Comedy', 'Drama', 'Family', 'Fantasy', 'Adventure', 'Adventure', 'Action', 'Comedy', 'Music', 'Drama', 'Romance', 'Adventure', 'Comedy', 'Drama', 'Romance', 'Drama', 'Romance', 'Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Comedy', 'Romance', 'Comedy', 'Romance', 'Drama', 'Drama', 'Thriller', 'Crime', 'Drama', 'Thriller', 'Science Fiction', 'Drama', 'Comedy', 'Music', 'Adventure', 'Animation', 'Comedy', 'Family', 'Drama', 'Romance', 'Action', 'Crime', 'Drama', 'Romance', 'Thriller', 'Western', 'Comedy', 'Drama', 'Crime', 'Horror', 'Mystery', 'Thriller', 'Science Fiction', 'Thriller', 'Romance', 'Drama', 'Comedy', 'Drama', 'Comedy', 'Romance', 'Fantasy', 'Drama', 'Action', 'Comedy', 'Science Fiction', 'Action', 'Thriller', 'Fantasy', 'Comedy', 'Romance', 'Drama', 'Horror', 'Thriller', 'Family', 'Action', 'Comedy', 'Drama', 'Adventure', 'Fantasy', 'Drama', 'Music', 'Thriller', 'Comedy', 'Drama', 'Comedy', 'Drama', 'Music', 'Romance', 'Comedy', 'Drama', 'Crime', 'Action', 'Thriller', 'Action', 'Animation', 'Action', 'Family', 'Action', 'Adventure', 'Crime', 'Drama', 'Comedy', 'Drama', 'Romance', 'Crime', 'Drama', 'Mystery', 'Romance', 'Thriller', 'Action', 'Adventure', 'Science Fiction', 'Thriller', 'Action', 'Adventure', 'Comedy', 'Fantasy', 'Drama', 'Crime', 'Action', 'Adventure', 'Comedy', 'Family', 'Family', 'Fantasy', 'Romance', 'Crime', 'Drama', 'Western', 'Comedy', 'Crime', 'Drama', 'Comedy', 'Horror', 'Drama', 'Science Fiction', 'Adventure', 'Action', 'Comedy', 'Drama', 'Romance', 'Drama', 'Fantasy', 'Horror', 'Mystery', 'Romance', 'Thriller', 'Comedy', 'Romance', 'Thriller', 'Crime', 'Drama', 'Mystery', 'Horror', 'Thriller', 'Romance', 'Romance', 'Thriller', 'Comedy', 'Romance', 'Comedy', 'Crime', 'Drama', 'War', 'Action', 'Comedy', 'Horror', 'Comedy', 'Music', 'Horror', 'Thriller', 'Comedy', 'Romance', 'Documentary', 'Drama', 'Thriller', 'History', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Comedy', 'Drama', 'Action', 'Adventure', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Drama', 'Romance', 'Adventure', 'Drama', 'Family', 'Action', 'History', 'War', 'Drama', 'Music', 'Romance', 'Drama', 'Thriller', 'Music', 'Comedy', 'Drama', 'Fantasy', 'Animation', 'Science Fiction', 'Family', 'Thriller', 'Horror', 'Action', 'Crime', 'Drama', 'Drama', 'Horror', 'Fantasy', 'Comedy', 'Drama', 'Action', 'Comedy', 'Thriller', 'Crime', 'Adventure', 'Fantasy', 'Drama', 'Romance', 'Action', 'Crime', 'Drama', 'Mystery', 'Thriller', 'Drama', 'Comedy', 'Romance', 'Drama', 'Adventure', 'Comedy', 'Crime', 'Mystery', 'Romance', 'Animation', 'Adventure', 'Comedy', 'Family', 'Drama', 'Thriller', 'Comedy', 'Drama', 'Romance', 'Drama', 'Comedy', 'Action', 'Drama', 'Thriller', 'Animation', 'Adventure', 'Family', 'Comedy', 'Adventure', 'Comedy', 'Family', 'Science Fiction', 'Drama', 'History', 'Romance', 'Drama', 'Drama', 'Thriller', 'Action', 'Thriller', 'Crime', 'Action', 'Thriller', 'Family', 'Science Fiction', 'Comedy', 'Crime', 'Drama', 'Comedy', 'Thriller', 'Action', 'Comedy', 'Crime', 'Drama', 'Drama', 'Action', 'Thriller', 'Horror', 'Science Fiction', 'Drama', 'Music', 'Romance', 'Fantasy', 'Family', 'R

In [ ]:
print(set(genere))

{'Drama', 'Mystery', 'Horror', 'Animation', 'Family', 'Comedy', 'TV Movie', 'Thriller', 'Documentary', 'Fantasy', 'Science Fiction', 'History', 'Action', 'Romance', 'Adventure', 'Music', 'War', 'Crime', 'Western', 'Foreign'}

In [ ]:
genere_df = pd.DataFrame(genere,columns = ['genere'])
genere_df['genere'].value_counts()

genere
Drama              1531
Comedy             1028
Thriller            789
Action              741
Romance             571
Crime               469
Adventure           439
Horror              301
Science Fiction     290
Family              260
Fantasy             232
Mystery             225
Animation           141
History             132
War                 100
Music               100
Documentary          87
Western              43
Foreign              31
TV Movie              1
Name: count, dtype: int64

In [ ]:
genere_df['genere'].unique()

array(['Comedy', 'Drama', 'Family', 'Romance', 'Thriller', 'Action',
       'Animation', 'Adventure', 'Horror', 'Documentary', 'Music',
       'Crime', 'Science Fiction', 'Mystery', 'Foreign', 'Fantasy', 'War',
       'Western', 'History', 'TV Movie'], dtype=object)

In [ ]:
genere_df['genere'].nunique()

20

#Q5.Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor.